name: Checks
on:
  push:
    branches:
      - main
      - "**"
    paths-ignore:
      - "**/README.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - develop
    paths-ignore:
      - "**/README.md"
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          skip-build: true
      - name: Lint
        run: |
          pnpm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          skip-build: true
      - name: Typecheck
        run: |
          pnpm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          skip-build: true
      - name: Test
        run: |
          pnpm run test --run
